export enum StepEnum {
  STEP_POST_CODE,
  STEP_WASTE_TYPE,
  STEP_SELECT_SKIP,
  STEP_PERMIT_CHECK,
  STEP_CHOOSE_DATE,
  STEP_PAYMENT,
}

export enum WasteTypeEnum {
  HOUSEHOLD_WASTE = 1,
  CONSTRUCTION_WASTE,
  GARDEN_WASTE,
  COMMERCIAL_WASTE,
}
